<?php
$mapeoRutas =
  [
    'inicio' =>
      ['controller' => 'ElectroVadillo\App\Controller\DefaultController', 'action' => 'inicio'],
      /*
    'iniSes' =>
      ['controller' => 'MiniBiblioteca\App\Controller\SessionController', 'action' => 'iniSes'],
    'saleSes' =>
      ['controller' => 'MiniBiblioteca\App\Controller\SessionController', 'action' => 'saleSes'],
    'usuDevuelveLibro' =>
      ['controller' => 'MiniBiblioteca\App\Controller\GestionLibrosController', 'action' => 'devolverLibro'],
    'usuTomaPrestado' =>
      ['controller' => 'MiniBiblioteca\App\Controller\GestionLibrosController', 'action' => 'tomarLibro'],
*/
  ];
